# Generated by Django 5.1.6 on 2025-03-16 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_asset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='asset',
            field=models.ImageField(blank=True, default='static\\image\\WEDING_3.jpeg', null=True, upload_to='event_asset'),
        ),
    ]
