# Generated by Django 5.1.6 on 2025-03-16 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_alter_event_asset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='asset',
            field=models.ImageField(blank=True, default='static\\image\\BALL_1.jpeg', null=True, upload_to='event_asset/'),
        ),
    ]
