# Generated by Django 5.1.6 on 2025-03-17 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_alter_event_asset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='asset',
            field=models.ImageField(blank=True, default='media\\event_asset\t-2.jpeg', null=True, upload_to='event_asset/'),
        ),
    ]
